# Generated by Django 3.0.6 on 2020-05-18 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commnet_content',
            new_name='comment_content',
        ),
    ]
